// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU98BQTD0XpBRXWcGsuvkO4qqYx3EbHRU',
    appId: '1:1045583437831:web:740ba6db06460e448a4aa2',
    messagingSenderId: '1045583437831',
    projectId: 'biz4x-remittance',
    authDomain: 'biz4x-remittance.firebaseapp.com',
    storageBucket: 'biz4x-remittance.firebasestorage.app',
    measurementId: 'G-40LT8Y4CMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6K2mvRqZAAvq0VMA0jf_-QbyGWA4rUSc',
    appId: '1:1045583437831:android:c5f2638d558d4c9f8a4aa2',
    messagingSenderId: '1045583437831',
    projectId: 'biz4x-remittance',
    storageBucket: 'biz4x-remittance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uv9kSBOAqGCUuuFlh6pWrrQMw7xWIZI',
    appId: '1:1045583437831:ios:16dabfc2f872e4c48a4aa2',
    messagingSenderId: '1045583437831',
    projectId: 'biz4x-remittance',
    storageBucket: 'biz4x-remittance.firebasestorage.app',
    iosClientId: '1045583437831-fqtai7l7i936fih3olmn3ko47584j8rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uv9kSBOAqGCUuuFlh6pWrrQMw7xWIZI',
    appId: '1:1045583437831:ios:16dabfc2f872e4c48a4aa2',
    messagingSenderId: '1045583437831',
    projectId: 'biz4x-remittance',
    storageBucket: 'biz4x-remittance.firebasestorage.app',
    iosClientId: '1045583437831-fqtai7l7i936fih3olmn3ko47584j8rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU98BQTD0XpBRXWcGsuvkO4qqYx3EbHRU',
    appId: '1:1045583437831:web:1a2dee60adc833a68a4aa2',
    messagingSenderId: '1045583437831',
    projectId: 'biz4x-remittance',
    authDomain: 'biz4x-remittance.firebaseapp.com',
    storageBucket: 'biz4x-remittance.firebasestorage.app',
    measurementId: 'G-HTD36HVFYX',
  );
}
