// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuPV735m2wGpkHC7OHPKzR9VhmZzJY6U',
    appId: '1:1049850024670:web:adc8ddef4ffec8d08c284f',
    messagingSenderId: '1049850024670',
    projectId: 'auth-1d805',
    authDomain: 'auth-1d805.firebaseapp.com',
    storageBucket: 'auth-1d805.firebasestorage.app',
    measurementId: 'G-S39GYGE405',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBelSNXqqkBjDVOL2QRjVBEaqb0E3H67LE',
    appId: '1:1049850024670:android:d0243c5c541eeb7b8c284f',
    messagingSenderId: '1049850024670',
    projectId: 'auth-1d805',
    storageBucket: 'auth-1d805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RCcG5AnXi_0XrmlpYiMc6Q4adAYNOJE',
    appId: '1:1049850024670:ios:24e6139a0f20eb098c284f',
    messagingSenderId: '1049850024670',
    projectId: 'auth-1d805',
    storageBucket: 'auth-1d805.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_RCcG5AnXi_0XrmlpYiMc6Q4adAYNOJE',
    appId: '1:1049850024670:ios:24e6139a0f20eb098c284f',
    messagingSenderId: '1049850024670',
    projectId: 'auth-1d805',
    storageBucket: 'auth-1d805.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzuPV735m2wGpkHC7OHPKzR9VhmZzJY6U',
    appId: '1:1049850024670:web:08143366d45f9f048c284f',
    messagingSenderId: '1049850024670',
    projectId: 'auth-1d805',
    authDomain: 'auth-1d805.firebaseapp.com',
    storageBucket: 'auth-1d805.firebasestorage.app',
    measurementId: 'G-0VWVWW4B0J',
  );
}
